method: random
metric:
  goal: minimize
  name: best_val_loss
parameters:
  embedding_dim:
    value: 512
  hla_embedding_dim:
    value: 1024
  PMA_num_heads:
    value: 4
  PMA_ln:
    value: True
  num_heads:
    value: 4
  transf_hidden_dim:
    value: 512
  n_attention_layers:
    value: 2
  accumulate_batches:
    value: 64
  batch_size:
    value: 16
  binding_affinity_df:
    value: /home/gvisona/SelfPeptides/processed_data/Binding_Affinity/DHLAP_binding_affinity_data.csv
  ligand_atlas_binding_df:
    value: "/home/gvisona/SelfPeptides/processed_data/Binding_Affinity/HLA_Ligand_Atlas_processed.csv"
  cool_down:
    value: 0.8
  experiment_group:
    value: DHLAP_binding_affinity_training_LS
  experiment_name:
    value: Binding_model_LS_lrfind_loss
  lr:
    distribution: log_uniform_values 
    max: 5.0e-3
    min: 5e-6
  momentum:
    value: 0.9
  nesterov_momentum:
    value: True
  max_updates:
    value: 5000
  min_frac:
    value: 0.1
  dropout_p:
    value: 0.05
  mlp_num_layers:
    value: 2
  mlp_hidden_dim:
    value: 2048
  output_dim:
    value: 1
  postprocessing_hidden_dim:
    value: 32
  project_folder:
    value: /fast/gvisona/SelfPeptides
  pseudo_seq_file:
    value: "/home/gvisona/SelfPeptides/processed_data/HLA_embeddings/HLA_pseudoseqs_T5/hla_pseudoseq_mapping.csv"
  hla_prot_seq_file:
    value: "/home/gvisona/SelfPeptides/processed_data/HLA_embeddings/HLA_proteins_T5/hla_proteins_mapping.csv"
  pseudoseq_seq2idx_file:
    value: "/home/gvisona/SelfPeptides/processed_data/HLA_embeddings/HLA_pseudoseqs_T5/pseudosequence2idx.json"
  pseudoseq_embeddings_file:
    value: "/home/gvisona/SelfPeptides/processed_data/HLA_embeddings/HLA_pseudoseqs_T5/hla_pseudoseqs_T5_embeddings.npy"
  protein_seq2idx_file:
    value: "/home/gvisona/SelfPeptides/processed_data/HLA_embeddings/HLA_proteins_T5/prot_sequence2idx.json"
  protein_embeddings_file:
    value: "/home/gvisona/SelfPeptides/processed_data/HLA_embeddings/HLA_proteins_T5/hla_proteins_T5_embeddings.npy"
  ramp_up:
    value: 0.1
  seed:
    distribution: int_uniform
    min: 0
    max: 100000
  test_size:
    value: 0.15
  val_size:
    value: 0.1
  validate_every_n_updates:
    value: 32
  weight_decay:
    value: 0.0001
  early_stopping:
    value: True
  patience:
    value: 200
  pretrained_aa_embeddings:
    value: "/home/gvisona/SelfPeptides/processed_data/aa_embeddings/learned_BA_AA_embeddings.npy"
  ls_alpha:
    values:
    - 0.1
  wandb_sweep:
    value: True