method: random
metric:
  goal: minimize
  name: best_val_loss
parameters:
  embedding_dim:
    values: 
    - 512
    - 1024
  PMA_num_heads:
    values: 
    - 1
    - 2
  PMA_ln:
    value: True
  num_heads:
    values: 
    - 4
    - 8
  transf_hidden_dim:
    value: 1024
  n_attention_layers:
    values: 
    - 2
    - 4
    - 8
    - 16
  accumulate_batches:
    value: 32
  batch_size:
    value: 16
  cool_down:
    value: 0.8
  experiment_group:
    value: Classifier_Embedder
  experiment_name:
    value: Hinge_loss_1
  lr:
    distribution: log_uniform_values 
    max: 1.0e-3
    min: 1e-7
  momentum:
    values: 
    - 0.9
    - 0.99
  nesterov_momentum:
    value: True
  max_updates:
    value: 100000
  min_frac:
    value: 0.1
  dropout_p:
    values: 
    - 0.0
    - 0.05
    - 0.1
  project_folder:
    value: /fast/gvisona/SelfPeptides
  ramp_up:
    value: 0.1
  seed:
    value: 0
  val_size:
    value: 5000
  gen_size:
    value: 1000000
  validate_every_n_updates:
    value: 16
  weight_decay:
    values: 
    - 0.0
    - 0.00001
    - 0.0001
  early_stopping:
    value: True
  patience:
    value: 10000
  hdf5_dataset:
    value: "/home/gvisona/SelfPeptides/processed_data/pre_tokenized_peptides_dataset.hdf5"