method: random
metric:
  goal: minimize
  name: val/loss
parameters:
  accumulate_batches:
    value: 1
  batch_size:
    value: 64
  cool_down:
    value: 0.8
  experiment_group:
    value: FinetuneESM2
  experiment_name:
    value: ESM_sweep_3_cont
  lr:
    value: 0.000000369224483345
  momentum:
    value: 0.99
  nesterov_momentum:
    value: True
  max_updates:
    value: 100000
  min_frac:
    value: 0.1
  project_folder:
    value: /fast/gvisona/SelfPeptides
  data_folder:
    value: /home/gvisona/SelfPeptides
  ramp_up:
    value: 0.1
  seed:
    value: 23217
  seed2:
    distribution: int_uniform
    min: 0
    max: 100000
  val_size:
    value: 0.1
  test_size:
    value: 0.15
  validate_every_n_updates:
    value: 10
  weight_decay:
    value: 1e-5
  early_stopping:
    value: False
  patience:
    value: 10000
  test_run:
    value: False
  wandb_sweep:
    value: True
  pretrained_model:
    value: "facebook/esm2_t12_35M_UR50D"
  mlm_fraction:
    value: 0.15
  peptides_dataframes:
    value:
      - "processed_data/Immunogenicity/Processed_TCell_IEDB_beta_summed.csv"
      - "processed_data/Immunogenicity/DHLAP_immunogenicity_data.csv"
      - "processed_data/Binding_Affinity/DHLAP_binding_affinity_data.csv"
      - "processed_data/Binding_Affinity/HLA_Ligand_Atlas_processed.csv"
  resume_checkpoint_path:
    value: /lustre/fast/fast/gvisona/SelfPeptides/outputs/FinetuneESM2/ESM_sweep_3/proud-sweep-12/checkpoints/001_checkpoint.pt
  force_restart:
    value: False