method: random
metric:
  goal: minimize
  name: val/loss
parameters:
  accumulate_batches:
    value: 8
  batch_size:
    value: 16
  cool_down:
    value: 0.8
  experiment_group:
    value: IEDB_BetaRegression_Regr
  experiment_name:
    value: Beta_ProtSeqs_Regr_long
  immunogenicity_df:
    value: /home/gvisona/SelfPeptides/processed_data/Immunogenicity/Processed_TCell_IEDB_beta_summed.csv
  dhlap_df:
    value: /home/gvisona/SelfPeptides/processed_data/Immunogenicity/DHLAP_immunogenicity_data.csv
  pseudo_seq_file:
    value: /home/gvisona/SelfPeptides/processed_data/HLA_embeddings/HLA_pseudoseqs_T5/hla_pseudoseq_mapping.csv
  hla_prot_seq_file:
    value: /home/gvisona/SelfPeptides/processed_data/HLA_embeddings/HLA_proteins_T5/hla_proteins_mapping.csv
  lr:
    distribution: log_uniform_values
    min: 1e-8
    max: 5e-6
  momentum:
    value: 0.99
  nesterov_momentum:
    value: True
  max_updates:
    value: 200000
  min_frac:
    value: 0.1
  project_folder:
    value: /fast/gvisona/Immunology
  ramp_up:
    value: 0.1
  seed:
    value: 10384
  test_size:
    value: 0.15
  val_size:
    value: 0.1
  validate_every_n_updates:
    value: 16
  weight_decay:
    value: 0.00001
  early_stopping:
    value: True
  patience:
    value: 200
  dropout_p:
    value: 0.05
  embedding_dim:
    value: 512
  mlp_input_dim:
    value: 1025
  mlp_hidden_dim:
    value: 2048
  mlp_num_layers:
    values: 
    - 2
    - 3
    - 4
  output_dim: 
    value: 2
  min_subjects_tested:
    value: 1
  pretrained_aa_embeddings:
    value: "/home/gvisona/SelfPeptides/processed_data/aa_embeddings/learned_BA_AA_embeddings.npy"
  binding_model_config:
    value: "/home/gvisona/SelfPeptides/trained_models/BindingModels/solar-sweep-1/config.json"
  binding_model_checkpoint:
    value: "/home/gvisona/SelfPeptides/trained_models/BindingModels/solar-sweep-1/checkpoints/001_checkpoint.pt"
  wandb_sweep:
    value: True
  use_posterior_mean:
    values:
    - True
    - False